In [44]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# 첫 번째 행 가져오기
arr1 = arr[0]
print(f"첫번째 행 : {arr1}")
#2번째 열만 가져오기
arr2 = arr[:,1]
print(f"2번째 열 : {arr2}")
#1행 1열~끝까지
arr3 = arr[1:, 1:]
print(f"1행 1열~끝까지 : {arr3}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
첫번째 행 : [1 2 3]
2번째 열 : [2 5 8]
1행 1열~끝까지 : [[5 6]
 [8 9]]


In [50]:
x, y = np.array([1, 2, 3]), np.array([4, 5, 6])

print(f"더하기 : {x+y}")
print(f"빼기 : {x-y}")
print(f"곱하기 : {x*y}")
print(f"나누기 : {x/y}")

더하기 : [5 7 9]
빼기 : [-3 -3 -3]
곱하기 : [ 4 10 18]
나누기 : [0.25 0.4  0.5 ]


In [46]:
list_data = [10, 20, 30, 40, 50]

numpy_list = np.array(list_data)

print(numpy_list)
print(type(numpy_list))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [47]:
data = np.genfromtxt('mini_ratings.csv', delimiter=",", dtype=float)

print(f"data 전체 : {data[1:]}")

print(f"처음 5행 : {data[1:6,:]}")

data 전체 : [[ 3.   6.   3.7]
 [ 5.  10.   3.1]
 [ 3.   2.   2.7]
 [ 1.   9.   1.7]
 [ 3.   8.   2.4]
 [ 2.   6.   3.2]
 [ 2.   5.   3.5]
 [ 3.   7.   3.1]
 [ 3.   9.   3.4]
 [ 4.   7.   3.1]
 [ 5.   9.   5. ]
 [ 4.  10.   3.6]
 [ 2.   4.   3.9]
 [ 1.   6.   1. ]
 [ 3.   5.   3.3]
 [ 1.   6.   1.8]
 [ 5.   3.   1.7]
 [ 1.   8.   4.7]
 [ 4.   5.   3.4]
 [ 3.   6.   3.2]]
처음 5행 : [[ 3.   6.   3.7]
 [ 5.  10.   3.1]
 [ 3.   2.   2.7]
 [ 1.   9.   1.7]
 [ 3.   8.   2.4]]


In [48]:
mean_ratings = data[1:,2].mean()
print(f"2번째 열(평점)의 평균 : {mean_ratings}")

2번째 열(평점)의 평균 : 3.075


In [49]:
user_ids=np.unique(data[1:,0])

print(f"사용자 아이디 :  {user_ids}")

mean_values=[]
for user_id in user_ids:
    # 유저가 남긴 모든 영화 평점에 대해서 모두 수집
    data_for_user=data[data[:,0]==user_id,:]
    # 수집된 모든 평점을 평균화
    value=data_for_user[:,2].mean()
    mean_values.append([user_id,value])

print(f"사용자 아이디 별 평균 값 : {mean_values}")

mean_array=np.array(mean_values,dtype=np.float32)

print(f"사용자 아이디 별 평균 값 : {mean_array[:5]}")

np.savetxt("result_mini_rating_mean.csv",mean_array,
           fmt="%.1f",delimiter=",")

사용자 아이디 :  [1. 2. 3. 4. 5.]
사용자 아이디 별 평균 값 : [[np.float64(1.0), np.float64(2.3)], [np.float64(2.0), np.float64(3.533333333333333)], [np.float64(3.0), np.float64(3.1142857142857143)], [np.float64(4.0), np.float64(3.3666666666666667)], [np.float64(5.0), np.float64(3.266666666666666)]]
사용자 아이디 별 평균 값 : [[1.        2.3      ]
 [2.        3.5333333]
 [3.        3.1142857]
 [4.        3.3666666]
 [5.        3.2666667]]
