In [12]:
import numpy as np
data = np.genfromtxt('ratings.dat', delimiter="::", dtype=np.int64, autostrip=True)

print("모든 데이터")
print(data)

#UserID	MovieID	Rating	Timestamp
print("처음 5행의 데이터")
print(data[:5,:])

print("데이터의 형(행, 열)")
print(data.shape)

mean_rating_total=data[:,2].mean() #data[:,2] 전체 행, 2번째 열
print("행의 평균")
print(mean_rating_total)

user_ids=np.unique(data[:,0])
print("사용자 아이디")
print(user_ids)
print(len(user_ids))

모든 데이터
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]
처음 5행의 데이터
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]
데이터의 형(행, 열)
(1000209, 4)
행의 평균
3.581564453029317
사용자 아이디
[   1    2    3 ... 6038 6039 6040]
6040
