In [12]:
import numpy as np
data = np.genfromtxt('ratings.dat', delimiter="::", dtype=np.int64, autostrip=True)

print("모든 데이터")
print(data)

#UserID	MovieID	Rating	Timestamp
print("처음 5행의 데이터")
print(data[:5,:])

print("데이터의 형(행, 열)")
print(data.shape)

mean_rating_total=data[:,2].mean() #data[:,2] 전체 행, 2번째 열
print("행의 평균")
print(mean_rating_total)

user_ids=np.unique(data[:,0])
print("사용자 아이디")
print(user_ids)
print(len(user_ids))

모든 데이터
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]
처음 5행의 데이터
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]
데이터의 형(행, 열)
(1000209, 4)
행의 평균
3.581564453029317
사용자 아이디
[   1    2    3 ... 6038 6039 6040]
6040


In [15]:
mean_values=[]
for user_id in user_ids:
    # 유저가 남긴 모든 영화 평점에 대해서 모두 수집
    data_for_user=data[data[:,0]==user_id,:]
    # 수집된 모든 평점을 평균화
    value=data_for_user[:,2].mean()
    mean_values.append([user_id,value])

mean_values[:5] # 전체에서 0~6번행까지만 출력

[[np.int64(1), np.float64(4.188679245283019)],
 [np.int64(2), np.float64(3.7131782945736433)],
 [np.int64(3), np.float64(3.9019607843137254)],
 [np.int64(4), np.float64(4.190476190476191)],
 [np.int64(5), np.float64(3.1464646464646466)]]

In [16]:
mean_array=np.array(mean_values,dtype=np.float32)
print(mean_array[:5])
print(mean_array.shape)

[[1.        4.188679 ]
 [2.        3.7131784]
 [3.        3.9019608]
 [4.        4.1904764]
 [5.        3.1464646]]
(6040, 2)


In [19]:
np.savetxt("/Users/ihanjo/Downloads/result.csv",mean_array,
           fmt="%.1f",delimiter=",")